[package]
name = "lyra-catalog-cli"
description = "Command line interface for the Lyra catalog."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "lyra-catalog"
path = "src/main.rs"

[dependencies]
lyra-catalog = { path = "../catalog" }
lyra-meta = { workspace = true }
arrow-array = { workspace = true }
arrow-flight = { workspace = true }
arrow-schema = { workspace = true }
clap = { workspace = true }
futures-util = { workspace = true }
libc = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
